/* [
    {
        name:'Jhanker Mahbub',
        img:'https://www.tbsnews.net/sites/default/files/styles/infograph/public/images/2021/07/08/img_2842_0.jpg?itok=styt4qgr',
        Role:'Senior Web Developer',
        ExpertIn:'Node JS',
        Experience:'10 Years',
        Salary:120000
    },
    {
        name:'Zaheed Sabur',
        img:'https://media-eng.dhakatribune.com/uploads/2019/05/web-zaheed-1556971049382.jpg',
        Role:'Front-end Web Developer',
        ExpertIn:'React JS',
        Experience:'7 Years',
        Salary:110000
    },
    {
        name:'Zulkernine Mahmud',
        img:'https://www.zulkarnine.com/wp-content/uploads/2020/07/PP.jpg',
        Role:'Back-end Web Developer',
        ExpertIn:'PHP',
        Experience:'5 Years',
        Salary:100000
    },
    {
        name:'Zulkernine Mahmud',
        img:'https://www.zulkarnine.com/wp-content/uploads/2020/07/PP.jpg',
        Role:'Back-end Web Developer',
        ExpertIn:'PHP',
        Experience:'5 Years',
        Salary:100000
    },
    {
        name:'Zulkernine Mahmud',
        img:'https://www.zulkarnine.com/wp-content/uploads/2020/07/PP.jpg',
        Role:'Back-end Web Developer',
        ExpertIn:'PHP',
        Experience:'5 Years',
        Salary:100000
    },
    {
        name:'Zulkernine Mahmud',
        img:'https://www.zulkarnine.com/wp-content/uploads/2020/07/PP.jpg',
        Role:'Back-end Web Developer',
        ExpertIn:'PHP',
        Experience:'5 Years',
        Salary:100000
    },
    {
        name:'Zulkernine Mahmud',
        img:'https://www.zulkarnine.com/wp-content/uploads/2020/07/PP.jpg',
        Role:'Back-end Web Developer',
        ExpertIn:'PHP',
        Experience:'5 Years',
        Salary:100000
    },
    {
        name:'Zulkernine Mahmud',
        img:'https://www.zulkarnine.com/wp-content/uploads/2020/07/PP.jpg',
        Role:'Back-end Web Developer',
        ExpertIn:'PHP',
        Experience:'5 Years',
        Salary:100000
    },
    {
        name:'Zulkernine Mahmud',
        img:'https://www.zulkarnine.com/wp-content/uploads/2020/07/PP.jpg',
        Role:'Back-end Web Developer',
        ExpertIn:'PHP',
        Experience:'5 Years',
        Salary:100000
    },
    {
        name:'Zulkernine Mahmud',
        img:'https://www.zulkarnine.com/wp-content/uploads/2020/07/PP.jpg',
        Role:'Back-end Web Developer',
        ExpertIn:'PHP',
        Experience:'5 Years',
        Salary:100000
    },
    {
        name:'Zulkernine Mahmud',
        img:'https://www.zulkarnine.com/wp-content/uploads/2020/07/PP.jpg',
        Role:'Back-end Web Developer',
        ExpertIn:'PHP',
        Experience:'5 Years',
        Salary:100000
    },
    {
        name:'Zulkernine Mahmud',
        img:'https://www.zulkarnine.com/wp-content/uploads/2020/07/PP.jpg',
        Role:'Back-end Web Developer',
        ExpertIn:'PHP',
        Experience:'5 Years',
        Salary:100000
    },
    {
        name:'Zulkernine Mahmud',
        img:'https://www.zulkarnine.com/wp-content/uploads/2020/07/PP.jpg',
        Role:'Back-end Web Developer',
        ExpertIn:'PHP',
        Experience:'5 Years',
        Salary:100000
    },
    {
        name:'Zulkernine Mahmud',
        img:'https://www.zulkarnine.com/wp-content/uploads/2020/07/PP.jpg',
        Role:'Back-end Web Developer',
        ExpertIn:'PHP',
        Experience:'5 Years',
        Salary:100000
    },
    {
        name:'Zulkernine Mahmud',
        img:'https://www.zulkarnine.com/wp-content/uploads/2020/07/PP.jpg',
        Role:'Back-end Web Developer',
        ExpertIn:'PHP',
        Experience:'5 Years',
        Salary:100000
    },
    
] */